import JSZip from 'jszip';

/**
 * Strip version suffix like _0.1 or _0_1 from a job name.
 * e.g. "Job_tFilterRow_v1_0.1" -> "Job_tFilterRow_v1"
 */
function stripVersionSuffix(name) {
  return name.replace(/_\d+[._]\d+$/, '');
}

/**
 * Generate a simple Python runner script that invokes the backend engine.
 */
function generatePythonRunner(jobDef, scriptName) {
  const jobName = jobDef.job_name || 'etl_job';

  return `#!/usr/bin/env python3
"""
Auto-generated ETL Job Runner: ${jobName}
Generated by DataPrep Studio

Usage:
    python ${scriptName} job.json
    python ${scriptName} job.json --context Production
    python -m src.v1.engine.engine job.json
    python -m src.v1.engine.engine job.json --context Production
"""

import sys
import subprocess
import argparse
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description='${jobName} — ETL Job Runner')
    parser.add_argument('job_file', nargs='?', default=None, help='Path to job.json (default: job.json next to this script)')
    parser.add_argument('--context', default=None, help='Context group name (e.g. Default, Production)')
    args = parser.parse_args()

    job_path = args.job_file if args.job_file else str(Path(__file__).parent / 'job.json')
    job_path = str(Path(job_path).resolve())

    cmd = [sys.executable, '-m', 'src.v1.engine.engine', job_path]
    if args.context:
        cmd.extend(['--context', args.context])

    print(f'Running engine: {" ".join(cmd)}')
    result = subprocess.run(cmd)
    sys.exit(result.returncode)


if __name__ == '__main__':
    main()
`;
}

/**
 * Generate requirements.txt from component types used.
 */
function generateRequirements(components) {
  const types = new Set(components.map((c) => c.original_type || c.type));
  const deps = ['# Core dependencies'];

  if (types.has('tFileInputExcel') || types.has('tFileOutputExcel')) {
    deps.push('openpyxl>=3.1.0');
  }
  if (types.has('tOracleConnection') || types.has('tOracleInput') || types.has('tOracleOutput') || types.has('tOracleRow')) {
    deps.push('cx_Oracle>=8.0.0');
    deps.push('# or: oracledb>=1.0.0');
  }
  if (types.has('tMSSqlConnection') || types.has('tMSSqlInput')) {
    deps.push('pyodbc>=4.0.0');
  }
  if (types.has('tPythonDataframe')) {
    deps.push('pandas>=2.0.0');
  }
  if (types.has('tFileInputXML') || types.has('tAdvancedFileOutputXML')) {
    deps.push('lxml>=4.9.0');
  }

  return deps.join('\n') + '\n';
}

/**
 * Generate config.ini from context variables.
 */
function generateConfig(jobDef) {
  const contexts = jobDef.context || {};
  const lines = ['# Auto-generated configuration for: ' + (jobDef.job_name || 'ETL Job'), ''];
  for (const [ctxName, vars] of Object.entries(contexts)) {
    lines.push(`[${ctxName}]`);
    for (const [k, v] of Object.entries(vars || {})) {
      const val = v && typeof v === 'object' && 'value' in v ? v.value : v;
      lines.push(`${k} = ${val}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * Generate README.md for the package.
 */
function generateReadme(jobDef, scriptName) {
  const name = jobDef.job_name || 'ETL Job';
  const comps = jobDef.components || [];
  const flows = jobDef.flows || [];

  const compList = comps.map((c) => `| ${c.id} | ${c.original_type} | ${c.type} |`).join('\n');
  const flowList = flows.map((f) => `| ${f.name || '-'} | ${f.from} | ${f.to} | ${f.type} |`).join('\n');

  return `# ${name}

Auto-generated ETL job package by DataPrep Studio.

## Quick Start

\`\`\`bash
# Run via backend engine
python -m src.v1.engine.engine job.json

# Or run via the generated script (wraps the engine call)
python ${scriptName}
python ${scriptName} job.json
\`\`\`

## Package Contents

| File | Description |
|---|---|
| \`job.json\` | Job definition (components, flows, schemas, triggers) |
| \`${scriptName}\` | Python runner script (calls backend engine) |
| \`requirements.txt\` | Python dependencies |
| \`config.ini\` | Context variables / runtime configuration |
| \`README.md\` | This file |

## Components (${comps.length})

| ID | Type | Category |
|---|---|---|
${compList || '| - | - | - |'}

## Data Flows (${flows.length})

| Name | From | To | Type |
|---|---|---|---|
${flowList || '| - | - | - | - |'}

## Configuration

Edit \`config.ini\` to change context variables for different environments:

\`\`\`ini
[Default]
# your variables here

[Production]
# production overrides
\`\`\`

## Customization

The \`${scriptName}\` script is a thin wrapper that calls:
\`\`\`
python -m src.v1.engine.engine job.json
\`\`\`

Edit \`job.json\` directly to modify the job definition.
Refer to \`job.json\` for the full component configuration and schema definitions.
`;
}

/**
 * Export a job as a ZIP package containing JSON + Python + config.
 * @param {string} jobJsonString - The job definition JSON string
 * @returns {Promise<Blob>} ZIP file blob
 */
export async function createJobPackage(jobJsonString) {
  const jobDef = JSON.parse(jobJsonString);
  const rawJobName = (jobDef.job_name || 'etl_job').replace(/\s+/g, '_');
  const cleanName = stripVersionSuffix(rawJobName);
  const scriptName = `run_${cleanName}.py`;

  const zip = new JSZip();
  const folder = zip.folder(rawJobName);

  // 1. Job definition JSON
  folder.file('job.json', JSON.stringify(jobDef, null, 2));

  // 2. Python runner (named after job)
  folder.file(scriptName, generatePythonRunner(jobDef, scriptName));

  // 3. Requirements
  folder.file('requirements.txt', generateRequirements(jobDef.components || []));

  // 4. Config
  folder.file('config.ini', generateConfig(jobDef));

  // 5. README
  folder.file('README.md', generateReadme(jobDef, scriptName));

  // Generate ZIP blob
  return zip.generateAsync({ type: 'blob' });
}
